//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseTime
    {
        public string site { get; set; }
        public string brand { get; set; }
        public string country { get; set; }
        public int resptime { get; set; }
        public Nullable<System.DateTime> mtts { get; set; }
    }
}
